spring:
    jpa:
        database: POSTGRES
    datasource:
        url: jdbc:postgresql://localhost:5432/event
        username: postgres
        password: postgres
        driver-class-name : org.postgresql.Driver
event:
    init: 
        init_quota_turn: 18
        init_quota_co2: 1500
        init_money: 1000
        init_quota_co2_perteam: 600
        init_sales: 1000
        init_earth: 2
        init_perteam: 3
        init_co2_gameover: false
    event:
        event_tree: true
        event_tree_quantity: 2
        event_sales: true
        event_sales_magnificant: 2
        event_not_clean_energy:
            - factory
            - factory_new
            - factory_automation
        event_emission_trading: 300
        event_reduction_quota_co2: 200
        event_subsidy: 200
        event_tax: -200
        event_other_clean_energy: 50
        event_other_solar_panel: 50

    