spring:
    jpa:
        database: POSTGRES
    datasource:
        url: jdbc:postgresql://localhost:5432/event
        username: postgres
        password: postgres
        driver-class-name : org.postgresql.Driver

event:
    quota: 
        ggp_quota_turn: 18
        ggp_quota_co2: 1500
        ggp_init_money: 1000
        ggp_init_quota_co2_perteam: 600
        ggp_init_sales: 1000
        ggp_init_earth: 2
        ggp_init_perteam: 3
        ggp_init_co2_gameover: disabled
    event:
        ggp_event_tree: enable
        ggp_event_tree_quantity: 2
        ggp_event_sales: enable
        ggp_event_sales_magnificant: 2
        ggp_event_not_clean_energy:
            - factory
            - factory_new
            - factory_automation
        ggp_event_emission_trading: 300
        ggp_event_reduction_quota_co2: 200
        ggp_event_subsidy: 200
        ggp_event_tax: -200
        ggp_other_clean_energy: 50
        ggp_other_solar_panel: 50

    